server:
      port: 2019
      context-path: /Employee-Management-System
spring:
     mvc:
       view:
          prefix: /
          suffix: .jsp
     datasource:
              driverClassName: oracle.jdbc.driver.OracleDriver
              url: jdbc:oracle:thin:@localhost:1521:xe
              username: system
              password: durgesh  